site_name: Lagrangian FiLM NN
repo_url: https://github.com/matteocorbetta/lagrangian-film-nn
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
nav:
  - Home: index.md
  - Background: background.md
  - How The Model Works: how-the-model-works.md
  - Results: results.md
  - API: api.md
